# Fly.io deployment configuration for Shimmy
app = "shimmy-ai"
primary_region = "iad"

[build]
dockerfile = "deploy/Dockerfile"

[http_service]
internal_port = 11434
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "30s"
interval = "30s"
method = "GET"
path = "/health"
timeout = "5s"

[env]
RUST_LOG = "info"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024