# Cargo configuration to speed up builds and prevent hangs

[build]
# Use parallel compilation but limit to prevent hangs
jobs = 4

# Environment variables for llama.cpp compilation
[env]
# Enable CUDA compilation for GPU support
LLAMA_CUDA = "ON"
GGML_CUDA = "ON"
# Use faster compilation flags
CMAKE_BUILD_TYPE = "Release"
# Limit parallel jobs for llama.cpp to prevent hanging
CMAKE_BUILD_PARALLEL_LEVEL = "4"
# CUDA architecture - use all-major for broad compatibility
CMAKE_CUDA_ARCHITECTURES = "all-major"
